import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import axios from 'axios';
import crypto from 'crypto';
import fs from 'fs-extra';
import os from 'os';
import path from 'path';
import { PassThrough } from 'node:stream';
import sharp from 'sharp';
import { IMAGE_BLOBS_DIR } from './config';
import { hydrateMessagesForProvider, putImageBlob, readImageRef, resolveImageBlobPath } from './imageBlobs';
import { convertToOpenAIResponsesFormat } from './llmProviders/openai';
import { deduplicateProviderRequestImages } from './providerImageDedup';
import type { Message, MessagePart } from './types';

const dataRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'foxwarm-image-storage-'));
fs.ensureDirSync(path.join(dataRoot, 'state'));
process.env.FOXWARM_DATA_DIR = dataRoot;

after(() => {
  fs.removeSync(dataRoot);
  delete process.env.FOXWARM_DATA_DIR;
});

async function makePng(color: { r: number; g: number; b: number }): Promise<Buffer> {
  return sharp({ create: { width: 4, height: 3, channels: 3, background: color } }).png().toBuffer();
}

function generatedPart(overrides: Record<string, any> = {}): MessagePart {
  const part = {
    imageMeta: { imageId: 'ig_one', origin: 'generated' as const, mimeType: 'image/png' },
    providerMeta: {
      openaiResponses: {
        sourceModelId: 'p/model',
        outputItem: { type: 'image_generation_call', id: 'ig_one', status: 'completed', output_format: 'png' },
      },
    },
    ...overrides,
  };
  return part as MessagePart;
}

test('identical generated bytes from separate calls share one Blob but keep both call records', async () => {
  const png = await makePng({ r: 1, g: 2, b: 3 });
  const first = await putImageBlob({ buffer: png, mimeType: 'image/png', imageId: 'ig_a' });
  const second = await putImageBlob({ buffer: png, mimeType: 'image/png', imageId: 'ig_b' });
  try {
    assert.equal(first.blobId, second.blobId);
    assert.notEqual(first.imageId, second.imageId);
    const messages: Message[] = [{
      role: 'model',
      parts: [
        generatedPart({
          inlineData: { data: png.toString('base64'), mimeType: 'image/png' },
          imageMeta: { imageId: 'ig_a', origin: 'generated', mimeType: 'image/png' },
          providerMeta: { openaiResponses: { sourceModelId: 'p/model', outputItem: { type: 'image_generation_call', id: 'ig_a', status: 'completed' } } },
        }),
        generatedPart({
          inlineData: { data: png.toString('base64'), mimeType: 'image/png' },
          imageMeta: { imageId: 'ig_b', origin: 'generated', mimeType: 'image/png' },
          providerMeta: { openaiResponses: { sourceModelId: 'p/model', outputItem: { type: 'image_generation_call', id: 'ig_b', status: 'completed' } } },
        }),
      ],
    }];

    // Prompt-level dedup must not strip assistant generated images from native replay.
    const deduped = deduplicateProviderRequestImages(messages, 'openai-responses');
    assert.ok(deduped.messages[0].parts.every((part: any) => !!part.inlineData));

    const input = convertToOpenAIResponsesFormat(structuredClone(messages), 'p/model');
    const calls = input.filter((item: any) => item.type === 'image_generation_call');
    assert.equal(calls.length, 2);
    assert.deepEqual(calls.map((call: any) => call.id), ['ig_a', 'ig_b']);
    assert.ok(calls.every((call: any) => call.result === png.toString('base64')));
  } finally {
    await fs.remove(resolveImageBlobPath(first.blobId!));
  }
});

test('canonical blob references rehydrate after a simulated restart without provider history', async () => {
  const png = await makePng({ r: 9, g: 8, b: 7 });
  const ref = await putImageBlob({ buffer: png, mimeType: 'image/png', imageId: 'ig_restart' });
  try {
    // Canonical persisted form: blob reference plus safe metadata, no base64.
    const canonical: Message[] = [{
      role: 'model',
      parts: [{
        inlineDataRef: ref,
        imageMeta: { imageId: 'ig_restart', origin: 'generated', mimeType: 'image/png', sha256: ref.sha256 },
        providerMeta: {
          openaiResponses: {
            sourceModelId: 'p/model',
            outputItem: { type: 'image_generation_call', id: 'ig_restart', status: 'completed', output_format: 'png' },
          },
        },
      }],
    }];
    assert.equal(JSON.stringify(canonical).includes(png.toString('base64')), false);

    const hydrated = await hydrateMessagesForProvider(structuredClone(canonical));
    const input = convertToOpenAIResponsesFormat(hydrated, 'p/model');
    assert.equal(input.length, 1);
    assert.equal(input[0].type, 'image_generation_call');
    assert.equal(input[0].result, png.toString('base64'));
    assert.deepEqual(await readImageRef(ref), png);
  } finally {
    await fs.remove(resolveImageBlobPath(ref.blobId!));
  }
});

test('a missing generated image fails explicitly instead of sending a dangling call', async () => {
  const missingRef = {
    imageId: 'ig_missing',
    blobId: `${crypto.createHash('sha256').update('absent').digest('hex')}.png`,
    mimeType: 'image/png',
    byteLength: 12,
    sha256: crypto.createHash('sha256').update('absent').digest('hex'),
  };
  const canonical: Message[] = [{
    role: 'model',
    parts: [{
      inlineDataRef: missingRef,
      imageMeta: { imageId: 'ig_missing', origin: 'generated', mimeType: 'image/png' },
      providerMeta: {
        openaiResponses: {
          sourceModelId: 'p/model',
          outputItem: { type: 'image_generation_call', id: 'ig_missing', status: 'completed', output_format: 'png' },
        },
      },
    }],
  }];
  await assert.rejects(() => hydrateMessagesForProvider(structuredClone(canonical)), /ENOENT|no such file/i);

  // Without hydrated bytes the replay must refuse rather than emit an id alone.
  assert.throws(
    () => convertToOpenAIResponsesFormat(structuredClone(canonical), 'p/model'),
    /local image bytes are missing or unreadable/,
  );
});

test('user-uploaded images keep the normal user input_image path with no fabricated roles', () => {
  const userImage: Message = {
    role: 'user',
    parts: [
      { text: 'edit this' },
      { inlineData: { data: 'AAAA', mimeType: 'image/png' }, imageMeta: { imageId: 'upload_1', origin: 'uploaded', mimeType: 'image/png' } },
    ],
  };
  const input = convertToOpenAIResponsesFormat([userImage], 'p/model');
  assert.equal(input.length, 1);
  assert.equal(input[0].type, 'message');
  assert.equal(input[0].role, 'user');
  const types = input[0].content.map((part: any) => part.type);
  assert.deepEqual(types, ['input_text', 'input_image']);
  assert.equal(input[0].content[1].image_url, 'data:image/png;base64,AAAA');
});

test('a local blob write failure reports a non-retryable failure without a second generation request', async () => {
  const png = await makePng({ r: 4, g: 5, b: 6 });
  const sha = crypto.createHash('sha256').update(png).digest('hex');
  const shardDir = path.join(IMAGE_BLOBS_DIR, sha.slice(0, 2));
  // Occupy the shard directory path with a file so blob persistence fails.
  await fs.ensureDir(IMAGE_BLOBS_DIR);
  await fs.writeFile(shardDir, 'not a directory');

  const { requestLlmOnce } = await import('./llm');
  const originalPost = axios.post;
  let calls = 0;
  (axios as any).post = async () => {
    calls += 1;
    const stream = new PassThrough();
    process.nextTick(() => {
      stream.write(`data: ${JSON.stringify({ type: 'response.completed', response: {
        id: 'r', status: 'completed',
        output: [{ type: 'image_generation_call', id: 'ig_write_fail', status: 'completed', output_format: 'png', result: png.toString('base64') }],
        usage: { input_tokens: 1, output_tokens: 1 },
      } })}\n\n`);
      stream.write('data: [DONE]\n\n');
      stream.end();
    });
    return { status: 200, statusText: 'OK', headers: {}, data: stream };
  };

  try {
    await assert.rejects(
      () => requestLlmOnce({
        contents: [{ role: 'user', parts: [{ text: 'draw' }] }],
        systemPrompt: '',
        modelEntryOverride: {
          providerKey: 'p', providerType: 'openai-responses', canonicalModelKey: 'p/model',
          baseUrl: 'https://responses.test/v1', model: 'model', extraFields: {}, extraHeaders: {},
          effort: { allowed: ['none', 'low', 'medium', 'high', 'xhigh', 'max'], default: 'high' },
          imageGeneration: { enabled: true, outputFormat: 'png' },
        } as any,
        toolDefinitions: [], notifySessionEvents: false, registerAbortController: false, maxRetries: 3,
      }),
      /image|Image/,
    );
    // A started image call is never transparently retried after a local failure.
    assert.equal(calls, 1);
  } finally {
    (axios as any).post = originalPost;
    await fs.remove(shardDir);
  }
});
